//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Check_Print.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Account
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Account()
        {
            this.DastehCheck = new HashSet<DastehCheck>();
        }
    
        public int Hesab_Id { get; set; }
        public Nullable<int> Bank_id { get; set; }
        public string Hesab_Name { get; set; }
        public string Hesab_Number { get; set; }
        public string Branch_Name { get; set; }
        public string Branch_Tel { get; set; }
        public string Branch_Adress { get; set; }
        public string Meli_Code { get; set; }
    
        public virtual Bank Bank { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DastehCheck> DastehCheck { get; set; }
    }
}
