//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Check_Print.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Check
    {
        public int Check_Id { get; set; }
        public Nullable<int> DC_Id { get; set; }
        public Nullable<int> Status_Id { get; set; }
        public Nullable<int> Serial { get; set; }
        public string SDate { get; set; }
        public string RDate { get; set; }
        public string Darvajh { get; set; }
        public string Mablagh { get; set; }
        public Nullable<int> User_id { get; set; }
    
        public virtual DastehCheck DastehCheck { get; set; }
        public virtual Status Status { get; set; }
        public virtual User User { get; set; }
    }
}
