//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Check_Print.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class DastehCheck
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DastehCheck()
        {
            this.Check = new HashSet<Check>();
        }
    
        public int DC_Id { get; set; }
        public string DC_Name { get; set; }
        public string DC_GSerial { get; set; }
        public Nullable<int> DC_Hesab_Id { get; set; }
        public Nullable<int> DC_Start { get; set; }
        public Nullable<int> DC_End { get; set; }
        public Nullable<int> Print_Formate_Id { get; set; }
    
        public virtual Account Account { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Check> Check { get; set; }
        public virtual PrintFormat PrintFormat { get; set; }
    }
}
