//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Check_Print.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PrintFormat
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PrintFormat()
        {
            this.DastehCheck = new HashSet<DastehCheck>();
        }
    
        public int PF_Id { get; set; }
        public string PF_Name { get; set; }
        public byte[] Pf_Pic { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DastehCheck> DastehCheck { get; set; }
        public virtual PrintFormatDimention PrintFormatDimention { get; set; }
    }
}
