//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Check_Print.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PrintFormatDimention
    {
        public int Pfd_id { get; set; }
        public Nullable<int> Pfd_PF_id { get; set; }
        public Nullable<int> Pfd_Row { get; set; }
        public Nullable<int> Pfd_x { get; set; }
        public Nullable<int> Pfd_y { get; set; }
        public Nullable<bool> Pfd_Valid { get; set; }
        public string Pfd_Font { get; set; }
        public Nullable<int> Pfd_Size { get; set; }
    
        public virtual PrintFormat PrintFormat { get; set; }
    }
}
